${{ datatype }}:
  description: Description for `${{ datatype }}`.
  properties:
    ${{ field }}:
      type: ${{ type }}
      x-summary: Summary for ${{ field }}
      description: Description for `${{ field }}`
