openapi: 3.0.2
info:
  title: PlanetSide 2 API Reference
  description: >
    These are community-maintained, inofficial docs for the
    [PlanetSide 2](https://www.planetside2.com/) API.


    This documentation is not endorsed by or affiliated with the
    PlanetSide 2 developer team or publisher.

    ***

    For more informaiton, visit the project repository at
    <https://github.com/leonhard-s/ps2-api-docs>.
  version: "0.1"
  termsOfService: https://census.daybreakgames.com#services-api-policy
servers:
  - url: https://census.daybreakgames.com/get/
paths:
  "/ps2:v2/character":
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  character_list:
                    type: array
                    items:
                      $ref: "#/components/schemas/character"
                  results:
                    type: integer
                    minimum: 0
              example:
                value:
                  $ref: "./components/examples/character.json"
